root = "."
tmp_dir = ".tmp"

[build]
  args_bin = []
  bin = "./.tmp/platform"
  cmd = "go build -o .tmp/platform ."
  delay = 1000
  exclude_dir = ["files", "infra", "static", "templates"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = [".", "log", "db", "middleware", "routes", "utils"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = ["main.go"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 1000
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
